version: "2"

linters:
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - errorlint
    - revive
    - ginkgolinter
    - govet
    - errname
    - err113

  settings:
    revive:
      rules:
      - name: unused-parameter
        severity: warning
        disabled: true

formatters:
  enable:
    - gofmt

run:
  timeout: 5m
