/*
Copyright 2026 Red Hat

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// gen-uid-gid-yaml marshals users.Registry to zz_generated_uid_gid.yaml
// for container image builds.
//
// Usage: go run ./cmd/gen-uid-gid-yaml
package main

import (
	"fmt"
	"os"
	"sort"

	"github.com/openstack-k8s-operators/lib-common/modules/users"
	"gopkg.in/yaml.v3"
)

func main() {
	// Sort keys for deterministic output
	names := make([]string, 0, len(users.Registry))
	for name := range users.Registry {
		names = append(names, name)
	}
	sort.Strings(names)

	ordered := yaml.Node{Kind: yaml.MappingNode}
	for _, name := range names {
		svc := users.Registry[name]
		svcNode := yaml.Node{}
		if err := svcNode.Encode(svc); err != nil {
			fmt.Fprintf(os.Stderr, "error encoding %s: %v\n", name, err)
			os.Exit(1)
		}
		ordered.Content = append(ordered.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: name},
			&svcNode,
		)
	}

	root := yaml.Node{
		Kind: yaml.MappingNode,
		Content: []*yaml.Node{
			{Kind: yaml.ScalarNode, Value: "services"},
			&ordered,
		},
	}
	doc := yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{&root}}

	if err := writeYAML(&doc); err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}
}

func writeYAML(doc *yaml.Node) error {
	out, err := os.Create("zz_generated_uid_gid.yaml")
	if err != nil {
		return fmt.Errorf("error creating output file: %w", err)
	}
	defer func() { _ = out.Close() }()

	header := []string{
		"# Code generated by gen-uid-gid-yaml from users.Registry. DO NOT EDIT.",
		"#",
		"# Central UID/GID registry for service containers.",
		"# Consumed by container image builds (useradd/groupadd).",
		"# Source of truth: registry.go",
	}
	for _, line := range header {
		if _, err := fmt.Fprintln(out, line); err != nil {
			return fmt.Errorf("error writing header: %w", err)
		}
	}

	enc := yaml.NewEncoder(out)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return fmt.Errorf("error writing YAML: %w", err)
	}
	return enc.Close()
}
