name: Golang lint, vet and unit test pipeline

on: [push, pull_request]

jobs:
  test:
    name: github (govet, golint and gotest)
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: 1.24.x
      - name: Checkout project code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Run govet.sh
        run: make govet
      - name: Run golint.sh
        run: make golint
      - name: Run gotest.sh
        run: make gotest

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
    - name: skip branch check
      run: echo "SKIP=no-commit-to-branch" >> "$GITHUB_ENV"
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      with:
        extra_args: --all-files --show-diff-on-failure --verbose
